version: "3"
services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    expose:
      - "3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://app_user:secret@db:5432/test_db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: app_user #In production this role should not be the same as the one used for the connection
      PGRST_SERVER_PROXY_URI: "http://127.0.0.1:3000"
    depends_on:
      - db
  db:
    image: postgres
    container_name: local_pgdb
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: shlomi@test.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    links:
      - "db:pgsql-server"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://127.0.0.1:3000/
  # Uncomment this if you want to persist the data.
volumes:
  local_pgdata:
  pgadmin-data:
