version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432: 5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

postgrest:
  image: postgrest/postgrest
  restart: always
  ports:
    - 3000:3000
  environment:
    PGRST_DB_URI: postgres://postgres:postgres@postgres:5432/postgres
    PGRST_DB_SCHEMA: public
    PGRST_DB_ANON_ROLE: postgres
    PGRST_SERVER_PROXY_URI: https
